// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// augment_g_collapsed_rcpp
NumericVector augment_g_collapsed_rcpp(NumericVector interval_sums, List v_obs, double kappa, NumericVector prob_g, NumericVector r, LogicalVector g_fixed);
RcppExport SEXP _BayesPIM_augment_g_collapsed_rcpp(SEXP interval_sumsSEXP, SEXP v_obsSEXP, SEXP kappaSEXP, SEXP prob_gSEXP, SEXP rSEXP, SEXP g_fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type interval_sums(interval_sumsSEXP);
    Rcpp::traits::input_parameter< List >::type v_obs(v_obsSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob_g(prob_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type g_fixed(g_fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(augment_g_collapsed_rcpp(interval_sums, v_obs, kappa, prob_g, r, g_fixed));
    return rcpp_result_gen;
END_RCPP
}
// fc_kappa_rcpp
double fc_kappa_rcpp(List v_obs, NumericVector j_, double a, double b, NumericVector g, NumericVector r, LogicalVector g_fixed);
RcppExport SEXP _BayesPIM_fc_kappa_rcpp(SEXP v_obsSEXP, SEXP j_SEXP, SEXP aSEXP, SEXP bSEXP, SEXP gSEXP, SEXP rSEXP, SEXP g_fixedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type v_obs(v_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type j_(j_SEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type g_fixed(g_fixedSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_kappa_rcpp(v_obs, j_, a, b, g, r, g_fixed));
    return rcpp_result_gen;
END_RCPP
}
// interval_probs_rcpp
List interval_probs_rcpp(NumericVector pobs_vec, List v_obs, NumericVector v_obs_l, NumericVector v_obs_r, NumericMatrix cur_dist_par_t, std::string dist);
RcppExport SEXP _BayesPIM_interval_probs_rcpp(SEXP pobs_vecSEXP, SEXP v_obsSEXP, SEXP v_obs_lSEXP, SEXP v_obs_rSEXP, SEXP cur_dist_par_tSEXP, SEXP distSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pobs_vec(pobs_vecSEXP);
    Rcpp::traits::input_parameter< List >::type v_obs(v_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v_obs_l(v_obs_lSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v_obs_r(v_obs_rSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cur_dist_par_t(cur_dist_par_tSEXP);
    Rcpp::traits::input_parameter< std::string >::type dist(distSEXP);
    rcpp_result_gen = Rcpp::wrap(interval_probs_rcpp(pobs_vec, v_obs, v_obs_l, v_obs_r, cur_dist_par_t, dist));
    return rcpp_result_gen;
END_RCPP
}
// look_up_mat_rcpp
NumericMatrix look_up_mat_rcpp(List v_obs, IntegerVector interval_indices);
RcppExport SEXP _BayesPIM_look_up_mat_rcpp(SEXP v_obsSEXP, SEXP interval_indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type v_obs(v_obsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type interval_indices(interval_indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(look_up_mat_rcpp(v_obs, interval_indices));
    return rcpp_result_gen;
END_RCPP
}
// p_v_obs_rcpp
List p_v_obs_rcpp(List v_obs, double kappa);
RcppExport SEXP _BayesPIM_p_v_obs_rcpp(SEXP v_obsSEXP, SEXP kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type v_obs(v_obsSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(p_v_obs_rcpp(v_obs, kappa));
    return rcpp_result_gen;
END_RCPP
}
// sample_k_rcpp
IntegerVector sample_k_rcpp(List pobs_norm);
RcppExport SEXP _BayesPIM_sample_k_rcpp(SEXP pobs_normSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type pobs_norm(pobs_normSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_k_rcpp(pobs_norm));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayesPIM_augment_g_collapsed_rcpp", (DL_FUNC) &_BayesPIM_augment_g_collapsed_rcpp, 6},
    {"_BayesPIM_fc_kappa_rcpp", (DL_FUNC) &_BayesPIM_fc_kappa_rcpp, 7},
    {"_BayesPIM_interval_probs_rcpp", (DL_FUNC) &_BayesPIM_interval_probs_rcpp, 6},
    {"_BayesPIM_look_up_mat_rcpp", (DL_FUNC) &_BayesPIM_look_up_mat_rcpp, 2},
    {"_BayesPIM_p_v_obs_rcpp", (DL_FUNC) &_BayesPIM_p_v_obs_rcpp, 2},
    {"_BayesPIM_sample_k_rcpp", (DL_FUNC) &_BayesPIM_sample_k_rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayesPIM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
