# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
augment_C_Rcpp <- function(pobs, Vobs, X, kappa, theta1, r, g_fixed) {
    .Call('_BayesPIM_augment_C_Rcpp', PACKAGE = 'BayesPIM', pobs, Vobs, X, kappa, theta1, r, g_fixed)
}

#' @export
augment_C_collapsed_rcpp <- function(w_sums, Vobs, kappa, theta1, r, g_fixed) {
    .Call('_BayesPIM_augment_C_collapsed_rcpp', PACKAGE = 'BayesPIM', w_sums, Vobs, kappa, theta1, r, g_fixed)
}

#' @export
fc_kappa_rcpp <- function(Vobs, j_, a, b, g, r, g_fixed) {
    .Call('_BayesPIM_fc_kappa_rcpp', PACKAGE = 'BayesPIM', Vobs, j_, a, b, g, r, g_fixed)
}

#' @export
lookUpMat_rcpp <- function(L, a) {
    .Call('_BayesPIM_lookUpMat_rcpp', PACKAGE = 'BayesPIM', L, a)
}

#' @export
NULL

#' @export
NULL

#' @export
P_vobs_Rcpp <- function(Vobs, kappa) {
    .Call('_BayesPIM_P_vobs_Rcpp', PACKAGE = 'BayesPIM', Vobs, kappa)
}

#' @export
pdist_rcpp <- function(q, par, dist) {
    .Call('_BayesPIM_pdist_rcpp', PACKAGE = 'BayesPIM', q, par, dist)
}

#' @export
pnorm_rcpp <- function(pobs_vec, Vobs, Vobs_L, Vobs_R, cur_par_X, dist_X, collapsed_g) {
    .Call('_BayesPIM_pnorm_rcpp', PACKAGE = 'BayesPIM', pobs_vec, Vobs, Vobs_L, Vobs_R, cur_par_X, dist_X, collapsed_g)
}

#' @export
sample_k_rcpp <- function(pobs_norm) {
    .Call('_BayesPIM_sample_k_rcpp', PACKAGE = 'BayesPIM', pobs_norm)
}

