# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

augment_g_collapsed_rcpp <- function(interval_sums, v_obs, kappa, prob_g, r, g_fixed) {
    .Call(`_BayesPIM_augment_g_collapsed_rcpp`, interval_sums, v_obs, kappa, prob_g, r, g_fixed)
}

fc_kappa_rcpp <- function(v_obs, j_, a, b, g, r, g_fixed) {
    .Call(`_BayesPIM_fc_kappa_rcpp`, v_obs, j_, a, b, g, r, g_fixed)
}

interval_probs_rcpp <- function(pobs_vec, v_obs, v_obs_l, v_obs_r, cur_dist_par_t, dist) {
    .Call(`_BayesPIM_interval_probs_rcpp`, pobs_vec, v_obs, v_obs_l, v_obs_r, cur_dist_par_t, dist)
}

look_up_mat_rcpp <- function(v_obs, interval_indices) {
    .Call(`_BayesPIM_look_up_mat_rcpp`, v_obs, interval_indices)
}

p_v_obs_rcpp <- function(v_obs, kappa) {
    .Call(`_BayesPIM_p_v_obs_rcpp`, v_obs, kappa)
}

sample_k_rcpp <- function(pobs_norm) {
    .Call(`_BayesPIM_sample_k_rcpp`, pobs_norm)
}

